### ISSUE TITLE
CoSTAR instructor UI windows behave very strangely after fix

### ISSUE THREAD

**Issue by cpaxton** [cpaxton/costar_stack#37]

**Comment by cpaxton** [comment]
Duplication: switching between windows when loading, or when subtree is loading

**Comment by fjonath1** [comment]
Fixed with commit [e264295ba6569a7135b7420e41f6b22d87286b97](https://github.com/cpaxton/costar_stack/commit/e264295ba6569a7135b7420e41f6b22d87286b97).

Seems like `setParent(None)` is not necessary if we do `hide()` and `show()` on the widget.
Adding `setParent(None)` on `clear_node_info` will only makes the ui slower without any benefits.
